// =============================================================
//  GAME STATE SINGLETON
//  All systems read and mutate this shared object.
// =============================================================

import type { GameState } from './types';

export const state: GameState = {
  coins: 100,
  xp: 0,
  level: 1,
  day: 1,
  startTime: Date.now() / 1000,
  selectedTool: 'hand',
  selectedSeed: 'wheat',
  grid: [],
  inv: { wheat: 5 },
  buildings: [],
  penAnimals: {},
  prodQueues: {},
  orders: [],
  camX: 0,
  camY: 0,
  camScale: 1,
  particles: [],
  floats: [],
  stats: {
    harvested: 0,
    sold: 0,
    planted: 0,
    produced: 0,
    plowed: 0,
    earned: 100,
    animalsOwned: 0,
    ordersFulfilled: 0,
    questsDone: 0,
    fishCaught: 0,
    decorsPlaced: 0,
    treesGrown: 0,
    crowsShooed: 0,
    itemsProduced: {},
  },
  placing: null,
  quests: [],
  achievements: {},
  season: 'spring',
  seasonDay: 1,
  weather: 'sunny',
  weatherUntil: 0,
  event: null,
  eventCooldown: 0,
  penFeed: {},
  decor: [],
  trees: [],
  crows: [],
  dog: null,
  fishing: null,
  musicOn: true,
  sfxOn: true,
};
